import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import style from './global.css'
import default_theme from './theme';
import { ThemeProvider } from '@mui/material';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <ThemeProvider theme={default_theme}>
      <html lang="en">
        <body className={style.body}>{children}</body>
      </html>
    </ThemeProvider>
  )
}
